<<webpackエラー>>
# 概要：circleci/config.ymlの記述とエラー内容

## ①- run: bundle exec bin/webpack  を入れる前
↓
Failure/Error: <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     
ActionView::Template::Error:
 Webpacker can't find application.js in /home/circleci/repec-exercise-sho/src/public/packs-test/manifest.json. Possible causes:
 1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
 2. webpack has not yet re-run to reflect updates.
 3. You have misconfigured Webpacker's config/webpacker.yml file.
 4. Your webpack configuration is not creating a manifest.
 Your manifest contains:
 {
 }


webpackerは/myapp/public/packs/manifest.jsonの中でapplication.jsを見つけることができません

可能性のある原因:
1. あなたが'webpack -w'かwebpack-deb-serverを使用しているのではない限り, webpacker.ymlのcompileの値を環境に合わせてtrueに設定してください。
2. webpackはアップデートを反映するための再実行がまだされていない
3. あなたは webpackerのconfig/webpacker.ymlファイルの設定が間違っています
4. あなたのwebpackの設定はmanifestを作っていません

あなたのmanifestが含んでいるもの:
{
}


※ちなみにwebpackerは、gemfile.lockにて
「webpacker (5.4.0)」

root@6078acb68783:/# find ./ -name "webpacker"
↓
./root/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info/webpacker
./usr/local/bundle/gems/webpacker-5.4.0/lib/tasks/webpacker
./usr/local/bundle/gems/webpacker-5.4.0/lib/webpacker
./app/node_modules/@rails/webpacker
./app/tmp/cache/webpacker
./app/vendor/bundle/ruby/2.7.0/gems/webpacker-5.4.0/lib/tasks/webpacker
./app/vendor/bundle/ruby/2.7.0/gems/webpacker-5.4.0/lib/webpacker



## ② - run: bundle exec bin/webpack  を入れた後
↓
bundler: not executable: bin/webpack
=> Gemfile.lockにwebpackerはあるが、webpackはないから。




----------------------------

# bundle configの表示

!/bin/bash -eo pipefail
bundle config
Settings are listed in order of priority. The top value will be used.

①path
Set for your local app (/usr/local/bundle/config): "./vendor/bundle"
 =>※実際にディレクトリ内部を見てみた。
 root@0d9996aa1e82:/usr/local/bundle# cat config
 ---
 BUNDLE_SET: "path vendor/bundle"


②jobs
Set via BUNDLE_JOBS: 3
 =>bundle installの並列処理


③app_config
Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
 =>bundlerの設定ファイルが格納されるディレクトリ


④silence_root_warning
Set via BUNDLE_SILENCE_ROOT_WARNING: true
 => gemをrootとしてインストールするときにBundlerが出力する警告を無音にします。


⑤retry
Set via BUNDLE_RETRY: 3
 =>失敗したネットワーク要求を再試行する回数。デフォルトは3。



※※ $ gem environment
root@0d9996aa1e82:/app# gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.6

  - RUBY VERSION: 2.7.4 (2021-07-07 patchlevel 191) [x86_64-linux]

  ★INSTALLATION DIRECTORY: /usr/local/bundle

  ★USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.7.0

  ★RUBY EXECUTABLE: /usr/local/bin/ruby
  =>Ruby実行時のRubyのパス

  ★GIT EXECUTABLE: /usr/bin/git

  ★EXECUTABLE DIRECTORY: /usr/local/bundle/bin

  - SPEC CACHE DIRECTORY: /root/.gem/specs

  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc

  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux

  - GEM PATHS: =>gemのパス
     - /usr/local/bundle
     - /root/.gem/ruby/2.7.0
     - /usr/local/lib/ruby/gems/2.7.0

  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-document"
     - "update" => "--no-document"

  - REMOTE SOURCES:
     - https://rubygems.org/

  - SHELL PATH:
     - /usr/local/bundle/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin


=======================================
<<webpackエラー>>

# error概要
circle ci test jobにて、

bundle exec rails db:migrate
=> 
bundler: command not found: rails
Install missing gem executables with `bundle install`



#予測
bundle exec 参照のrailsコマンドが実行されない。
bundleの参照位置がおかしい？



# 解析
コンテナ内へ。
$ docker container exec -it rspec_exercise_web_1 bash


bundleコマンドのありかを表示
$ which bundle
=> /usr/local/bin/bundle

bundle exec railsコマンドのありかを表示
$ which bundle exec rails
（/usr/local/bin/bundle）
/usr/local/bundle/bin/rails


PATHの確認
$ echo $PATH
/usr/local/bundle/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin


/usr/local/bin/bundleの内容を表示
$ cat /usr/local/bin/bundle
=>
#!/usr/local/bin/ruby（←localのrubyを参照）
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('bundler', 'bundle', version)
else
gem "bundler", version
load Gem.bin_path("bundler", "bundle", version)
end

